CREATE SCHEMA IF NOT EXISTS raw;

DROP TABLE IF EXISTS raw.mock_data;

CREATE TABLE raw.mock_data (
    raw_row_id bigserial PRIMARY KEY,
    source_file text NOT NULL,
    source_row_number integer NOT NULL,
    imported_at timestamptz NOT NULL DEFAULT now(),
    id text,
    customer_first_name text,
    customer_last_name text,
    customer_age text,
    customer_email text,
    customer_country text,
    customer_postal_code text,
    customer_pet_type text,
    customer_pet_name text,
    customer_pet_breed text,
    seller_first_name text,
    seller_last_name text,
    seller_email text,
    seller_country text,
    seller_postal_code text,
    product_name text,
    product_category text,
    product_price text,
    product_quantity text,
    sale_date text,
    sale_customer_id text,
    sale_seller_id text,
    sale_product_id text,
    sale_quantity text,
    sale_total_price text,
    store_name text,
    store_location text,
    store_city text,
    store_state text,
    store_country text,
    store_phone text,
    store_email text,
    pet_category text,
    product_weight text,
    product_color text,
    product_size text,
    product_brand text,
    product_material text,
    product_description text,
    product_rating text,
    product_reviews text,
    product_release_date text,
    product_expiry_date text,
    supplier_name text,
    supplier_contact text,
    supplier_email text,
    supplier_phone text,
    supplier_address text,
    supplier_city text,
    supplier_country text
);

CREATE TEMP TABLE raw_csv_import (
    import_row_number bigserial PRIMARY KEY,
    id text,
    customer_first_name text,
    customer_last_name text,
    customer_age text,
    customer_email text,
    customer_country text,
    customer_postal_code text,
    customer_pet_type text,
    customer_pet_name text,
    customer_pet_breed text,
    seller_first_name text,
    seller_last_name text,
    seller_email text,
    seller_country text,
    seller_postal_code text,
    product_name text,
    product_category text,
    product_price text,
    product_quantity text,
    sale_date text,
    sale_customer_id text,
    sale_seller_id text,
    sale_product_id text,
    sale_quantity text,
    sale_total_price text,
    store_name text,
    store_location text,
    store_city text,
    store_state text,
    store_country text,
    store_phone text,
    store_email text,
    pet_category text,
    product_weight text,
    product_color text,
    product_size text,
    product_brand text,
    product_material text,
    product_description text,
    product_rating text,
    product_reviews text,
    product_release_date text,
    product_expiry_date text,
    supplier_name text,
    supplier_contact text,
    supplier_email text,
    supplier_phone text,
    supplier_address text,
    supplier_city text,
    supplier_country text
);

DO $$
DECLARE
    csv_file text;
BEGIN
    FOR csv_file IN
        SELECT file_name
        FROM pg_ls_dir('/source-data') AS file_name
        WHERE file_name ILIKE '%.csv'
        ORDER BY file_name
    LOOP
        TRUNCATE TABLE raw_csv_import RESTART IDENTITY;

        EXECUTE format(
            'COPY raw_csv_import (
                id,
                customer_first_name,
                customer_last_name,
                customer_age,
                customer_email,
                customer_country,
                customer_postal_code,
                customer_pet_type,
                customer_pet_name,
                customer_pet_breed,
                seller_first_name,
                seller_last_name,
                seller_email,
                seller_country,
                seller_postal_code,
                product_name,
                product_category,
                product_price,
                product_quantity,
                sale_date,
                sale_customer_id,
                sale_seller_id,
                sale_product_id,
                sale_quantity,
                sale_total_price,
                store_name,
                store_location,
                store_city,
                store_state,
                store_country,
                store_phone,
                store_email,
                pet_category,
                product_weight,
                product_color,
                product_size,
                product_brand,
                product_material,
                product_description,
                product_rating,
                product_reviews,
                product_release_date,
                product_expiry_date,
                supplier_name,
                supplier_contact,
                supplier_email,
                supplier_phone,
                supplier_address,
                supplier_city,
                supplier_country
            ) FROM %L WITH (FORMAT csv, HEADER true, QUOTE ''"'', ESCAPE ''"'')',
            '/source-data/' || csv_file
        );

        INSERT INTO raw.mock_data (
            source_file,
            source_row_number,
            id,
            customer_first_name,
            customer_last_name,
            customer_age,
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            product_price,
            product_quantity,
            sale_date,
            sale_customer_id,
            sale_seller_id,
            sale_product_id,
            sale_quantity,
            sale_total_price,
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            product_weight,
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            product_rating,
            product_reviews,
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        )
        SELECT
            csv_file,
            import_row_number::integer,
            id,
            customer_first_name,
            customer_last_name,
            NULLIF(customer_age, ''),
            customer_email,
            customer_country,
            customer_postal_code,
            customer_pet_type,
            customer_pet_name,
            customer_pet_breed,
            seller_first_name,
            seller_last_name,
            seller_email,
            seller_country,
            seller_postal_code,
            product_name,
            product_category,
            NULLIF(product_price, ''),
            NULLIF(product_quantity, ''),
            sale_date,
            NULLIF(sale_customer_id, ''),
            NULLIF(sale_seller_id, ''),
            NULLIF(sale_product_id, ''),
            NULLIF(sale_quantity, ''),
            NULLIF(sale_total_price, ''),
            store_name,
            store_location,
            store_city,
            store_state,
            store_country,
            store_phone,
            store_email,
            pet_category,
            NULLIF(product_weight, ''),
            product_color,
            product_size,
            product_brand,
            product_material,
            product_description,
            NULLIF(product_rating, ''),
            NULLIF(product_reviews, ''),
            product_release_date,
            product_expiry_date,
            supplier_name,
            supplier_contact,
            supplier_email,
            supplier_phone,
            supplier_address,
            supplier_city,
            supplier_country
        FROM raw_csv_import;
    END LOOP;
END $$;

CREATE INDEX idx_mock_data_source_file_id ON raw.mock_data (source_file, source_row_number);
CREATE INDEX idx_mock_data_source_customer ON raw.mock_data (source_file, sale_customer_id);
CREATE INDEX idx_mock_data_source_seller ON raw.mock_data (source_file, sale_seller_id);
CREATE INDEX idx_mock_data_source_product ON raw.mock_data (source_file, sale_product_id);
